Use Appleboy

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -25,28 +25,34 @@ jobs:
         docker cp extract:/app/trackme ./trackme
         docker rm extract
 
+    - name: Copy assets and templates
+      uses: appleboy/scp-action@v0.1.7
+      with:
+        host: ${{ secrets.SERVER_IP }}
+        username: ${{ secrets.SERVER_USER }}
+        key: ${{ secrets.SSH_PRIVATE_KEY }}
+        port: 22
+        source: "trackme,assets,templates"
+        target: "~/track-me-temp/"
+
     - name: Deploy to server
-      env:
-        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
-        SERVER_USER: ${{ secrets.SERVER_USER }}
-        SERVER_IP: ${{ secrets.SERVER_IP }}
-      run: |
-        eval ssh-agent -s
-        echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
-        ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "mkdir -p ~/track-me-temp"
-        scp -r trackme assets templates $SERVER_USER@$SERVER_IP:~/track-me-temp/
-        ssh $SERVER_USER@$SERVER_IP << 'EOF'
-          ~/track-me-temp/trackme --ping
-          if [ $? -eq 0 ]; then
-            echo "New binary test passed. Proceeding with deployment."
-            sudo systemctl stop trackme.service
-            mv ~/track-me-temp/trackme /root/track-me/trackme
-            mv ~/track-me-temp/assets /root/track-me/assets
-            mv ~/track-me-temp/templates /root/track-me/templates
-            sudo systemctl start trackme.service
-          else
-            echo "New binary test failed. Aborting deployment."
-            exit 1
-          fi
-          rm -rf ~/track-me-temp
-        EOF
+      uses: appleboy/ssh-action@v1.0.3
+      with:
+        host: ${{ secrets.SERVER_IP }}
+        username: ${{ secrets.SERVER_USER }}
+        key: ${{ secrets.SSH_PRIVATE_KEY }}
+        port: 22
+        script: |
+            ~/track-me-temp/trackme --ping
+            if [ $? -eq 0 ]; then
+              echo "New binary test passed. Proceeding with deployment."
+              sudo systemctl stop trackme.service
+              mv ~/track-me-temp/trackme /root/track-me/trackme
+              mv ~/track-me-temp/assets /root/track-me/assets
+              mv ~/track-me-temp/templates /root/track-me/templates
+              sudo systemctl start trackme.service
+            else
+              echo "New binary test failed. Aborting deployment."
+              exit 1
+            fi
+            rm -rf ~/track-me-temp/*
